In [25]:
#question 1
# Create one hot encoding of an array.

import numpy as np

a = np.array([2, 3, 2, 2, 2, 1])
new_array= np.zeros((a.size, a.max()))
# print(a.size)
# print(a.max()+1)
# print(a.max())
# print(new_array)
# print(a)
new_array[np.arange(a.size),a-1] = 1
print(new_array)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [8]:
#question 2.
#Drop all missing values from an array 
# Input: np.array([1,2,3,np.nan,5,6,7,np.nan])
# Desired Output: array([ 1.,2.,3.,5.,6.,7.])
import numpy as np

a=np.array([1,2,3,np.nan,5,6,7,np.nan])
new_array=a[~np.isnan(a)]
print(new_array)



[1. 2. 3. 5. 6. 7.]


In [23]:
#question 3
#Find Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) 
#Desired Output: array([2, 5])


import numpy as np
a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) 

print(a)
local_max = np.array([])
for i in range(0, (len(a)-1)):
    current=i
    if (a[current-1]<a[current] and a[current]>a[current+1]):
        local_max=np.append(local_max, current)   


print (local_max)



[1 3 7 1 2 6 0 1]
[2. 5.]


In [49]:
#quesstion 4
#From the given 1d array arr, generate a 2d matrix using strides,

#last array (n) will be= n.s+w=N
import math
a=np.array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

w= 4
s=2
total_arrays=math.floor((len(a)-w)/s)+1
ans= np.ones((total_arrays,w))
# print(ans)

for i in range(total_arrays):
    start=s*i
    for j in range(w):
        ans[i][j]=a[start+j]
    
print(ans)


[[ 0.  1.  2.  3.]
 [ 2.  3.  4.  5.]
 [ 4.  5.  6.  7.]
 [ 6.  7.  8.  9.]
 [ 8.  9. 10. 11.]
 [10. 11. 12. 13.]]
